# Generated by Django 5.1.2 on 2025-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
